<?php

/**  
 * Implements hook_migrate_api().  
 */ 
// function hkmag_migrate_migrate_api() {   
//   $api = array(     
//     'api' => 2,
//     'groups' => array(
//         'hk_mag' => array(
//             'title' => t('HK Mag'),
//         ),
//     ),
// //     'migrations' => array(
// //         'HkmagRole' => array(
// //             'class_name' => 'HkmagRoleMigration',
// //             'group_name' => 'hk_mag',
// //         ),
// //     ),
//   );
 
//   return $api;
// }

function hkmag_migrate_flush_caches() {
  // Specify the DB connection and the source Drupal version.
  $common_arguments = array(
      'source_connection' => 'legacy',
      'source_version' => 6,
      'source_database' => array(
        'driver' => 'mysql',
        'database' => 'local_hkmag',
        'username' => 'local_hkmag', // Ideally this user has readonly access
        // Best practice: use a variable (defined by setting $conf in settings.php, or
        // with drush vset) for the password rather than exposing it in the code.
        'password' => 'local_hkmag',
        'host' => 'localhost',
        'prefix' => '',
      ),

  );

  // Register migrations.
//   _devblog_migrate_article($common_arguments);
//   _devblog_migrate_article_tags($common_arguments);
//   _devblog_migrate_users($common_arguments);
//   _devblog_migrate_files($common_arguments);
  _hkmag_migrate_migrate_term_country($common_arguments);
  _hkmag_migrate_migrate_term_topics($common_arguments);
  _hkmag_migrate_migrate_term_type($common_arguments);
  _hkmag_migrate_migrate_term_author($common_arguments);
  _hkmag_migrate_migrate_term_hk_area($common_arguments);
  _hkmag_migrate_migrate_term_hk_streets($common_arguments);
  _hkmag_migrate_migrate_term_place_cities($common_arguments);
  _hkmag_migrate_migrate_term_macau_street($common_arguments);
  _hkmag_migrate_migrate_term_macau_area($common_arguments);
  _hkmag_migrate_migrate_term_art_style($common_arguments);
  _hkmag_migrate_migrate_term_payment_accepted($common_arguments);
  _hkmag_migrate_migrate_term_tags($common_arguments);
  _hkmag_migrate_migrate_term_bar_ambiance($common_arguments);
  
  _hkmag_migrate_migrate_role($common_arguments);
  _hkmag_migrate_migrate_user($common_arguments);
  
  _hkmag_migrate_migrate_file($common_arguments);
  
  _hkmag_migrate_migrate_node_hotel($common_arguments);
  _hkmag_migrate_migrate_node_art_gallery($common_arguments);
  _hkmag_migrate_migrate_node_article($common_arguments);
  _hkmag_migrate_migrate_node_column_name($common_arguments);
  _hkmag_migrate_migrate_node_column_article($common_arguments);
  
}

function _hkmag_migrate_migrate_file($common_arguments) {
  // File migration
  $file_arguments = $common_arguments + array(
      'description' => t('Migrate all files'),
      'machine_name' => 'HkMagFile',
      'source_dir' => '/Users/Timothy/Sites/hk-magazine.com/html',
      'destination_dir' => '',
  );
  
  Migration::registerMigration('DrupalFile6Migration', $file_arguments['machine_name'], $file_arguments);
}

function _hkmag_migrate_migrate_term_country($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of country terms from Drupal 6'),
      'machine_name' => 'HkMagTermCountry',
      'source_vocabulary' => '106', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'country',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_topics($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of topics terms from Drupal 6'),
      'machine_name' => 'HkMagTermTopics',
      'source_vocabulary' => '170', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'topics',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_type($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of type terms from Drupal 6'),
      'machine_name' => 'HkMagTermType',
      'source_vocabulary' => '171', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'type',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_author($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of author terms from Drupal 6'),
      'machine_name' => 'HkMagTermAuthor',
      'source_vocabulary' => '152', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'author',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_hk_area($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of hk area terms from Drupal 6'),
      'machine_name' => 'HkMagTermHkArea',
      'source_vocabulary' => '181', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'hk_area',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_hk_streets($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of hk streets terms from Drupal 6'),
      'machine_name' => 'HkMagTermHkStreet',
      'source_vocabulary' => '180', // vid of th e Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'hk_streets',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_place_cities($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of hk area terms from Drupal 6'),
      'machine_name' => 'HkMagTermPlaceCities',
      'source_vocabulary' => '160', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'place_cities',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_macau_street($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of macau street terms from Drupal 6'),
      'machine_name' => 'HkMagTermMacauStreet',
      'source_vocabulary' => '252', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'macau_street',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}


function _hkmag_migrate_migrate_term_macau_area($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of macau area terms from Drupal 6'),
      'machine_name' => 'HkMagTermMacauArea',
      'source_vocabulary' => '253', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'macau_area',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_art_style($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of art style terms from Drupal 6'),
      'machine_name' => 'HkMagTermArtStyle',
      'source_vocabulary' => '147', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'art_style',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_payment_accepted($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of payment accepted terms from Drupal 6'),
      'machine_name' => 'HkMagTermPaymentAccepted',
      'source_vocabulary' => '9', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'payment_accepted',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_tags($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of tags terms from Drupal 6'),
      'machine_name' => 'HkMagTermTags',
      'source_vocabulary' => '3', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'tags',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_term_bar_ambiance($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of bar ambiance terms from Drupal 6'),
      'machine_name' => 'HkMagTermBarAmbiance',
      'source_vocabulary' => '145', // vid of the Drupal 6 ÒCategoriesÓ vocabulary
      'destination_vocabulary' => 'bar_ambiance',
  );
  // First argument is the migration class name
  Migration::registerMigration('DrupalTerm6Migration', $arguments['machine_name'],
  $arguments);
}
($common_arguments);


function _hkmag_migrate_migrate_user($common_arguments) {
  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
      'description' => t('Migration of users from Drupal 6'),
      'role_migration' => 'HkMagRoles',
      'machine_name' => 'HkMagUsers',
  );
  
  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('HkmagNodeUserMigration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_role($common_arguments) {
  
  $role_arguments = $common_arguments + array(
    'machine_name' => 'HkMagRoles',
    'description' => t('Import Drupal 6 roles'),
    'role_mappings' => array(
      'Admin' => 'Admin',
      'Editor' => 'Editor',
      'I.T. Admin' => 'I.T. Admin',
      'Managing Editor' => 'Managing Editor',
      'Marketing' => 'Marketing',
      'Moderator' => 'Moderator',
      'Premium Partner' => 'Premium Partner',
      'STB' => 'STB',
      'Sub Editor' => 'Sub Editor',
      'Writer' => 'Writer',
    ),
  );
  
  Migration::registerMigration('DrupalRole6Migration', $role_arguments['machine_name'], $role_arguments);
}

function _hkmag_migrate_migrate_node_hotel($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of node type hotel from Drupal 6'),
      'machine_name' => 'HkMagNodeHotel',
      'source_type' => 'hotel',
      'destination_type' => 'hotel',
      'user_migration' => 'HkMagUsers',  //
  );
  // First argument is the migration class name
  Migration::registerMigration('HkmagNodeHotelMigration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_node_art_gallery($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of node type art gallery from Drupal 6'),
      'machine_name' => 'HkMagNodeArtGallery',
      'source_type' => 'art_gallery',
      'destination_type' => 'art_gallery',
      'user_migration' => 'HkMagUsers',  //
  );
  // First argument is the migration class name
  Migration::registerMigration('HkmagNodeArtGalleryMigration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_node_article($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of node type article from Drupal 6'),
      'machine_name' => 'HkMagNodeArticle',
      'source_type' => 'articles',
      'destination_type' => 'article',
      'user_migration' => 'HkMagUsers',  //
  );
  // First argument is the migration class name
  Migration::registerMigration('HkmagNodeArticleMigration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_node_column_name($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of node type column name from Drupal 6'),
      'machine_name' => 'HkMagNodeColumnName',
      'source_type' => 'column_name',
      'destination_type' => 'column_name',
      'user_migration' => 'HkMagUsers',  //
  );
  // First argument is the migration class name
  Migration::registerMigration('HkmagNodeColumnNameMigration', $arguments['machine_name'],
  $arguments);
}

function _hkmag_migrate_migrate_node_column_article($common_arguments) {
  $arguments = $common_arguments + array(
      'description' => t('Migration of node type column article from Drupal 6'),
      'machine_name' => 'HkMagNodeColumnArticle',
      'source_type' => 'column_article',
      'destination_type' => 'column_article',
      'user_migration' => 'HkMagUsers',  //
  );
  // First argument is the migration class name
  Migration::registerMigration('HkmagNodeColumnArticleMigration', $arguments['machine_name'],
  $arguments);
}
